### ISSUE TITLE
Fix test execution sometimes hanging (OSOE-129)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Open-Source-Orchard-Core-Extensions#126]
Sometimes, for seemingly no good reason, the Tests step hangs and times out if we let it run. Let's fix this.

- See e.g.:
  - [This build](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/6678618135?check_suite_focus=true), logs: 
[logs_364.zip](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/files/8818394/logs_364.zip). Happened on Ubuntu.
  - [This one](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/2411631951/attempts/1) happened on Windows. Logs:
[logs_334.zip](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/files/8818416/logs_334.zip)
  - [Another one](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/2430943626), ironically happened when setting the workflow timeout as a stopgap to prevent them from running for 6 hours.
  - See others [under canceled Actions](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions?query=is%3Acancelled) (note that cancellation can be by the user's request too, a run is only interesting if it took one hour and was canceled by the system).
- It seems that the test run doesn't even start `dotnet test`. Maybe a command before that is hanging.

**Comment by Piedone** [comment]
This might have been fixed by accident after moving the test-executing code to PS. We need to see if new such occasions happen.

**Comment by Piedone** [comment]
Nope, [here's a recent one](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/7079986885?check_suite_focus=true).

**Comment by Piedone** [comment]
And [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/7084327991?check_suite_focus=true).

**Comment by Piedone** [comment]
Hmm, it seems that if we set maxParallelThreads = MaxParallelTests = 2 then it reliably gets stuck. See the previous ones, and [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/7092424975?check_suite_focus=true) and [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/7092671977?check_suite_focus=true). This coincides with the [Azure D2v2 VM used by GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#cloud-hosts-for-github-hosted-runners) having 2 vCores. However, when the issues was originally opened, we didn't have such config. Also, [this run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/7079986885?check_suite_focus=true) as with a parallelism of 4. Maybe the multiples of vCores cause an issue?

**Comment by Piedone** [comment]
Doesn't seem so. [Here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/7095286635?check_suite_focus=true) and [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/runs/7095449301?check_suite_focus=true) a run with a parallelism of 3 got stuck. Maybe it's the fifth test run that changes parallelism that always hangs.

**Comment by Piedone** [comment]
Perhaps _now_ it's fixed? No new timeouts since June.

**Comment by sarahelsaig** [comment]
I had a non-repeatable timeout in SNOW-119 just 2 days ago.

**Comment by Piedone** [comment]
Can you point to the build? It doesn't show up under https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions?query=is%3Acancelled, not I see any issues under https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/2848622770.

**Comment by sarahelsaig** [comment]
Ah, I didn't realize this issue was Actions-specific. Then disregard my previous comment. The timeout was [in TeamCity](https://ci.lombiq.com/buildConfiguration/WillisTowersWatson_Developer_PullAndBuild/1077632?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true).

**Comment by Piedone** [comment]
I see.

**Comment by Piedone** [comment]
There are still no such timeouts. I guess it solved itself, then. Good bug!
