### ISSUE TITLE
Problem building Lombiq.OSCCE (OSOE-384)

### ISSUE THREAD

**Issue by pbull001** [Lombiq/Open-Source-Orchard-Core-Extensions#207]
Hi,

I have clone the repo and installed all the pre-req (I think) and I am getting the following error:

"Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "pwsh -File C:\Users\User\source\repos\Lombiq2\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Invoke-Analyzer.ps1 -ForMsBuild" exited with code 1.	Lombiq.OSOCE.Web	C:\Users\User\source\repos\Lombiq2\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell.targets	41	
"

No sure were to go from here. Any pointers will be appreciated.

Thank you

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-384)

**Comment by 0liver** [comment]
Thanks for checking out our project! It looks like you might not have Powershell 7 installed which provides the `pwsh` command. Could you double-check?

**Comment by pbull001** [comment]
![image](https://user-images.githubusercontent.com/18185015/191763194-2eafe12c-ae41-4582-b79a-ca6ccac778cb.png)

**Comment by pbull001** [comment]
12>------ Build started: Project: Lombiq.OSOCE.Web, Configuration: Debug Any CPU ------
12>PowerShell 7.2.6
12>[91mSecurityError: [91mFile C:\Users\User\source\repos\Lombiq2\tools\Lombiq.Analyzers.PowerShell\Lombiq.Analyzers.PowerShell\Invoke-Analyzer.ps1 cannot be loaded

Found this in the Build Output

**Comment by sarahelsaig** [comment]
Did you initialize the submodules? If you browse to _C:\Users\User\source\repos\Lombiq2\tools\Lombiq.Analyzers.PowerShell_ is there anything in the directory? If not, then try `git submodule init; git submodule update`.

**Comment by pbull001** [comment]
> Did you initialize the submodules? If you browse to _C:\Users\User\source\repos\Lombiq2\tools\Lombiq.Analyzers.PowerShell_ is there anything in the directory? If not, then try `git submodule init; git submodule update`.

Yes - the files for a vs solution call Lombiq.Analyzers.PowerShell

**Comment by pbull001** [comment]
![image](https://user-images.githubusercontent.com/18185015/191774736-2f593220-bbc9-4883-b26c-02e76b9d9b9f.png)

**Comment by 0liver** [comment]
The `SecurityError` might be related to Powershell not trusting the source of the script. Please check the Execution Policy setting.

**Comment by pbull001** [comment]
> The `SecurityError` might be related to Powershell not trusting the source of the script. Please check the Execution Policy setting.

Yeah - trying to sort that out :)

**Comment by Piedone** [comment]
Did you manage to build the solution?

**Comment by pbull001** [comment]
> Did you manage to build the solution?

Thank you for the follow up :) I have put building the solution aside and am just integrating the modules into a play site to check them out. Resolving the policy question wasn't adding value immediately ;)

**Comment by Piedone** [comment]
OK, sure then!
