### ISSUE TITLE
Disable Jira issue title suffixes for submodules (OSOE-386)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Open-Source-Orchard-Core-Extensions#213]
Go through the _create-jira-issues-for-community-activities.yml_ workflows in all submodules, and set `suffix-issue-titles: "false"`. We don't actually need to include the component in the Jira issue titles since it's also readily visible not just in the issue detail view but in the kanban board too.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-386)

**Comment by sarahelsaig** [comment]
Why not make `suffix-issue-titles: "false"` the default value instead of setting it explicitly in every submodule? It fells like the less opinionated way to me.

**Comment by Piedone** [comment]
We can do that too, in that case, the other projects using this workflow need to be adapted. These are the following:

- OCC
- Dojo Library
- VSIX
- Hastlayer SDK
- DotNest Support
- DotNest Core SDK
- Utility Scripts

**Comment by Piedone** [comment]
Thinking about this, I think we should keep the suffix. While it might be superfluous in Jira, it doesn't hurt and can make things clearer (you look more at the issue's title at the top than its metadata somewhere down to the right), and it makes opening OSOCE PRs easier since you just need to copy the issue title to the PR title (otherwise the OSOCE PR's title would be something that perhaps only makes sense in the context of the submodule).

**Comment by Piedone** [comment]
So, let's not do this, then.
