### ISSUE TITLE
Update GitHub Actions workflows of all OSOCE projects from the OSS template (OSOE-485)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Open-Source-Orchard-Core-Extensions#301]
The [GitHub Actions workflows of our open-source repository template](https://github.com/Lombiq/Open-source-template/tree/dev/.github/workflows) now contain various smaller fixes, including but not necessarily limited to:

- The `types` parameter of GitHub Actions workflows should be arrays, even if they contain a single type, see [the docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows). E.g. it should be `[created]`, not `created`, even though the latter works too. The `create-jira-issues-for-community-activities` workflow didn't comply with this.
- The job names were fixed to relate to what the job actually does (there were copy-paste errors).
- `validate-submodule-pull-request` is now `validate-pull-request`, and its content also changed, but it still only executes the `validate-submodule-pull-request` workflow.

So, let's go through all OSOCE projects, and update these workflows from the template. Note that all three workflows may contain project-specific configuration, and `create-jira-issues-for-community-activities` at least has a unique `issue-component` for each project. So, simply overwriting the files is not enough, these configurations need to be retained.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-485)

**Comment by dorraj07** [comment]
How do I find " all OSOCE projects"?

**Comment by sarahelsaig** [comment]
It means all submodules in this repository. If you use Git Extensions ou can find them here:
![image](https://user-images.githubusercontent.com/4007293/214033224-7053f3bf-faa6-4b76-8658-085553f6465d.png)

**Comment by wAsnk** [comment]
@Piedone What does "The job names were fixed to relate to what the job actually does (there were copy-paste errors)." refer to?
I don't see any job names in the template repo.

**Comment by Piedone** [comment]
E.g. [this](https://github.com/Lombiq/Open-source-template/blob/dev/.github/workflows/validate-pull-request.yml#L7) is a job name. These changed.

**Comment by wAsnk** [comment]
Alrighty, so it's not an additional name property, got it.

**Comment by Piedone** [comment]
@DJdisco07 note:

> `validate-submodule-pull-request` is now `validate-pull-request`, and its content also changed, but **it still only executes the `validate-submodule-pull-request` workflow**.

This should point to the submodule workflow still (and the job name fixed to `validate-pull-request`): https://github.com/Lombiq/Orchard-Core-API-Client/blob/issue/OSOE-485/.github/workflows/validate-submodule-pull-request.yml#L9
