### ISSUE TITLE
Test branch builds with GitRunners (OSOE-599)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Open-Source-Orchard-Core-Extensions#435]
[GitRunners](https://gitrunners.com/) is a cheaper and perhaps faster option than using the larger runners GitHub provides. Let's test it for our larger runner builds.

- It's similar to [BuildJet](https://buildjet.com/) but that was only for Linux and we had issues with those runners being in parity with GitHub's.
- GitRunners' Linux runner is significantly cheaper: E.g. $0,0128 for a 4-core Linux instead of [GitHub's $0,016](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates). They don't offer Windows runners though.
- "Upcoming features  Persistent storage for all ephemeral runners and flamegraph visualizations to analize workflows runtimes." Persistent storage may help us a lot with repeated builds for private repos (due to not having to do a full rebuild, and NuGet/NPM package cache being initialized, faster than with GitHub Actions Cache).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-599)

**Comment by Piedone** [comment]
This is promising. The builds just worked, without having to change anything.

See the below spreadsheet for details:

[Measurements.xlsx](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/files/11083082/Measurements.xlsx)

### Larger runner benchmarks

- [OSOCE benchmark build](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4532727358)
- [Hastlayer SDK benchmark build](https://github.com/Lombiq/Hastlayer-SDK/actions/runs/4533741412)

In OSOCE, we get ~22% faster builds for ~35% cheaper. In Hastlayer, it's ~27% faster for ~44% cheaper. Seems like a no-brainer. There can be a wait time for GitRunners runners though, what I can't quantify, but I've seen it somewhat more than GitHub's; altogether the builds still all finished before the GitHub runners.

### Small runner benchmarks

When it comes to private repos (i.e. ones without free GitHub-hosted small runners) then it'd perhaps also make sense to use GitRunners 1-core runners instead of GitHub small runners for builds that can take however long (like `dev` builds). In this case, the question is only the price of the build (time doesn't matter and we expect it to be slower). This is only if we run out of the 3000 minutes that we get monthly.

I've done some measurements on this too, first for the **1-core runner**, see the spreadsheet for comparisons:

- [OSOCE benchmark build](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4533920187)
- [Hastlayer SDK benchmark build](https://github.com/Lombiq/Hastlayer-SDK/actions/runs/4533920758)

The money savings here are actually less, around 7% for OSOCE and 8% for Hastlayer. In the grand scheme of things, this would translate to about saving $11 a month perhaps (with 2000 overage minutes, so this is for the whole company, just extrapolating from the two measured repos).

Notable though that one of the test runs were aborted with this error:

```
[createdump] Gathering state for process 15470 dotnet
[createdump] Writing full dump to file /tmp/d7fdbe6b-de11-48f1-8fe1-0a3ad60de5d5/dotnet_15470_20230327T162802_hangdump.dmp
[createdump] Written 1541545984 bytes (376354 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written
Data collector 'Blame' message: The specified inactivity time of 5 minutes has elapsed. Collecting hang dumps from testhost and its child processes.
The active test run was aborted. Reason: Test host process crashed
Results File: /home/ubuntu/work/Open-Source-Orchard-Core-Extensions/Open-Source-Orchard-Core-Extensions/test/Lombiq.UITestingToolbox/Lombiq.Tests.UI.Samples/TestResults/test-results.trx

Test Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
Total tests: Unknown
```

See [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4533920187/jobs/7987391182#step:9:1397). This was also repeated for the 2-core benchmarks below but with the GitHub-hosted runner, see [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4534228114/jobs/7988130248). @dministro this is only because the test was slower than the hang dump timeout, something that we won't have once https://github.com/Lombiq/UI-Testing-Toolbox/issues/228 is fixed, right?

Measurements with 2-core GitHub runners vs **2-core** GitRunners runners:

- [OSOCE benchmark build](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4534228114)
- [Hastlayer SDK benchmark build](https://github.com/Lombiq/Hastlayer-SDK/actions/runs/4534229531)

Great savings of 67% for OSOCE and 70% for Hastlayer.  However, this is still around $10 monthly savings altogether. That is, if we were to switch over all of our private builds using standard runners, but I don't think we'd switch all the tiny PR validation ones, for example.

We'll need to check if switching over projects makes sense, since if we don't use much more than the included minutes, then the savings are small. In January we used 5900 additional minutes (but we messed up with a build that shouldn't have run, that used all of the included ones...), in February 1100 additional minutes, in March 4400 (but again we messed up). Even with 5900 additional minutes we're talking about a potential savings of $30 per month altogether. Not really worth the hassle of updating configs.

**Comment by dministro** [comment]
The https://github.com/Lombiq/UI-Testing-Toolbox/issues/228 is not totally fixed, we fixed some issues, but there is at least one which is out of the scope of `blame-hang-timeout`, so yes we can remove the `blame-hang-timeout` configuration if it is really necessary.

**Comment by Piedone** [comment]
We don't need to remove it now, just wanted to confirm what I'm seeing, thanks.

**Comment by BenedekFarkas** [comment]
I like those numbers percentagewise, although saving a few 10s of bucks per month doesn't worth it - it can ramp up later though. Also, it's an external company that would get access to our GitHub resources and repositories (but a greater benefit could justify that).

**Comment by Piedone** [comment]
The dollar savings I mentioned are for the workflows that use the small runners only (i.e. small projects, `dev` builds, and non-build workflows like `validate-pull-request`), not the ones with 4-cores and above. However, since those few large builds use as much compute time as all the small ones, the savings are indeed comparable (perhaps altogether $30-50). We'd save substantially with Windows builds if they were available. But the speed-up is really nice.

**Comment by 0liver** [comment]
Faster builds for less money sounds like a no-brainer 😉

**Comment by Piedone** [comment]
I was curious about 8-core runners. They'll surely be faster than the 2 or 4-core ones, but how will the price of builds compare?

I've updated the spreadsheet:

[Measurements.xlsx](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/files/11133017/Measurements.xlsx)

For OSOCE ([benchmark run here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4590065160)), compared to the 4-core builds there was a 13% speed increase for 75% higher price. For Hastlayer ([benchmark run here](https://github.com/Lombiq/Hastlayer-SDK/actions/runs/4590068972)), only a ~6% speed increase, for almost twice the price. So, apparently, for these two solutions the marginal utility drops sharply after 4 cores. I'd expect that larger solutions and/or

**Comment by Piedone** [comment]
I've merged the OSOCE and Hastlayer SDK PRs so we can test them (these builds are for public repos and don't use secrets), we can discuss the rest.

**Comment by BenedekFarkas** [comment]
We got word in the meanwhile that Windows image will soon be available as well.

> For OSOCE ([benchmark run here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4590065160)), compared to the 4-core builds there was a 13% speed increase for 75% higher price. For Hastlayer ([benchmark run here](https://github.com/Lombiq/Hastlayer-SDK/actions/runs/4590068972)), only a ~6% speed increase, for almost twice the price.

That's just because the solution's own limitation in terms of parallel builds or is there any difference (other than usually doubling the common resources) in the hardware?

**Comment by Piedone** [comment]
Ah yeah, I didn't finish the last sentence :D. Wanted to say that I'd expect that larger solutions and/or solutions with fewer dependencies between projects to get a speed up with more cores, even though the return will be always diminishing with core count, I've done benchmarks before with GitHub-hosted larger runners too, and we also then settled at the 4-core sweet spot. So, it's more of a thing of the solutions.

**Comment by Piedone** [comment]
Done some measurements with the new Windows runners. Benchmark builds [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620289266), [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620126991), and [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620564690) (only for OSOCE, since among our OSS projects we only use Windows builds here). Updated spreadsheet (see at the bottom):

[Measurements.xlsx](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/files/11161507/Measurements.xlsx)

Not as good of an improvement as with Ubuntu runners, unfortunately, but still good improvement. About 13% faster and 31% cheaper, though there were two exceptionally slow runs with GitHub-hosted runners (without those it'd be more like 6% faster and 25% cheaper).

Also, GitRunners said:

> It takes some minutes before the job starts. This problem also affects Linux runners but it is worse for Windows. Job start optimizations are on the roadmap and we are going to work on that independently from Windows.

This is indeed the case, but I've seen at most 2 minutes wait times, which is acceptable since the time you wait until you see build results is still at least about the same. I did see one instance with 16-core runners though, see below, when a runner wasn't started even within 17 minutes: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620576093/jobs/8170873630 Also, this one found a 16-core runner after 18 minutes: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620576093/jobs/8171217520 And this one I killed after it still didn't start after 40 minutes: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620847581/jobs/8171521587

![image](https://user-images.githubusercontent.com/1976647/230157654-5bf7855b-1374-43fc-b4c9-361c3dc48f4f.png)

Out of curiosity, I also tested with 16-core runners (only GitRunners ones, since we previously measured it to be uneconomical to use GitHub-hosted larger runners). See test builds [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620572626), [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620576093), [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620572626), [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620576093), and [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4620847581). Again, diminishing returns, but it's actually worse performance-wise than the 8-core one (9% speed increase over the GitHub-hosted 8-core runner and 32% more expensive)! I don't know why.

**Comment by BenedekFarkas** [comment]
During peak hours (in the overlapping time with the workday in most US time zones) GH Windows runners (even an 8-core one) can also take several minutes to spin up, so that's OK.
