### ISSUE TITLE
Update all packages to latest (OSOE-620)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Open-Source-Orchard-Core-Extensions#460]
...in all submodules too, once https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/378 is done.

- [x] When a UI test fails, currently an HTML snapshot is saved into the FailureDumps folder. This should rather be an MHTML with compatible Chromium browsers. This worked before but now it appears to revert back to HTML, perhaps due to some Chrome change. If this happens with the latest Atata too, then report it [here](https://github.com/atata-framework/atata/issues).
- [x] [`Microsoft.AspNetCore.Http`](https://www.nuget.org/packages/Microsoft.AspNetCore.Http/) is now deprecated. Remove it and use a substitute if necessary.
- [x] Don't forget about the NuGetTest solution.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-620)

**Comment by sarahelsaig** [comment]
> [`Microsoft.AspNetCore.Http`](https://www.nuget.org/packages/Microsoft.AspNetCore.Http/) is now deprecated. Remove it and use a substitute if necessary.

Correct me if I'm wrong, but as I understand only the NuGet package is deprecated. So we don't have to change code, just [use `<FrameworkReference>` instead of `<PackageReference>`](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-6.0&tabs=visual-studio#use-the-aspnet-core-shared-framework):

> With the release of .NET Core 3.0, many ASP.NET Core assemblies are no longer published to NuGet as packages. Instead, the assemblies are included in the `Microsoft.AspNetCore.App` shared framework, which is installed with the .NET Core SDK and runtime installers. For a list of packages no longer being published, see [Remove obsolete package references](https://learn.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-6.0#remove-obsolete-package-references).

**Comment by sarahelsaig** [comment]
Hmm, looks like we only have this problem in Lombiq.OrchardCoreApiClient which is `netstandard2.0` so the framework reference can't be used.  But it's only for a single `IFormFile Recipe` property in one of the API models. And that property is not used anywhere in OSOE, Lombiq-Tenants, or Dotnest-Tenants-Core. (is Lombiq.OrchardCoreApiClient used anywhere else?) I think it's safe to replace that property's type with `JToken`, so if anyone wants it they can still deserialize it as `IFormFile` in an assembly that has access to ASP.NET Core. Creating a new POCO that represents an `IFormFile` API response is an option too, but seems pointless.

**Comment by Piedone** [comment]
Next time before merging please actually wait for an answer. Also @Psichorex.

**Comment by sarahelsaig** [comment]
So what's the answer?

**Comment by sarahelsaig** [comment]
@Piedone We are still supposed to use `<TargetFramework>net6.0</TargetFramework>`, right? Because there is at least one package that couldn't be updated to the latest release version because

> Lombiq.Tests.csproj: [NU1202] Package Microsoft.AspNetCore.Mvc.Testing 7.0.8 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Microsoft.AspNetCore.Mvc.Testing 7.0.8 supports: net7.0 (.NETCoreApp,Version=v7.0)

**Comment by Piedone** [comment]
Add a new property, keep the old one with `[Obsolete]`, and document that removing the latter also needs the package reference removed. Then, we'll remove it with the next major release.

Yes, we still need to target .NET 6 (but build under the .NET 7 SDK).
