### ISSUE TITLE
Figure out how we can build and NuGet-publish projects that depend on Gulp Extensions (OSOE-84)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Open-Source-Orchard-Core-Extensions#48]
Currently, we commit the wwwroot folders instead of building them during publishing with [Gulp Extensions](https://github.com/Lombiq/Gulp-Extensions), which is bad. Instead, we should build static resources as we do in the OSOCE build, but we can't really do exactly that.

- Most possibly this needs changes to the affected projects and https://github.com/Lombiq/NuGet-Publishing-GitHub-Actions as well.
- Remove the note about this issue in the root OSOCE Readme too.
- This is a continuation of: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/23 An attempt was made and can be continued under https://github.com/Lombiq/Gulp-Extensions/pull/31.
- Adapt all GE-using projects of ours.
- Perhaps we can use the [Node.js Extensions project of ours](https://github.com/Lombiq/NodeJs-Extensions) that can make this easier.
- See @Skrypt's remarks here: https://github.com/OrchardCMS/OrchardCore/discussions/11294#discussioncomment-2296858
- Maybe we could `Exec` an NPM install or something? Perhaps the other NPM-related packages can be of some inspiration: https://www.nuget.org/packages?q=npm

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-84)

**Comment by Piedone** [comment]
We're doing this with the https://github.com/Lombiq/NodeJs-Extensions project, WIP for full support of what Gulp Extensions does.

**Comment by Piedone** [comment]
@scleaver @deanmarcussen it might be interesting for you what we've progressed with Node.js Extensions here. While we don't have the full functionality of Gulp Extensions yet, we actually have an NPM script-containing NuGet package working!

**Comment by 0liver** [comment]
Projects using our new [Node.js Extensions](https://github.com/Lombiq/NodeJs-Extensions) project can now be published to NuGet without further work.

To migrate from Gulp Extensions to Node.js Extensions, follow this guide: https://github.com/Lombiq/Gulp-Extensions/blob/dev/Docs/MigrationToNodeJsExtensions.md.
