### ISSUE TITLE
Configure YAML linting (OSOE-759)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Open-Source-Orchard-Core-Extensions#658]
After https://github.com/Lombiq/NodeJs-Extensions/issues/11, configure the YAML linting rules of [`yamllint`](https://github.com/adrienverge/yamllint) as it's fitting for our projects.

- [x] Check all the rules it has and enable/configure them, as well as fix the issues it uncovers. When in doubt, discuss it with the team.
- [x] Add the workflow to https://github.com/Lombiq/Hosting-Media-Theme too. - Not necessary, see: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/658#issuecomment-2211563957
- [x] For quotes, we'll need to use the following:

```json
quoted-strings: {
    quote-type: single,
    required: only-when-needed
}
```

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-759)

**Comment by DemeSzabolcs** [comment]
Regarding the rules I have one (currently), that I can't decide:

Should we allow implicit `null` values?

Example for implicit `null`: https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/deploy-orchard1-to-azure-app-service.yml#L42C7-L43
Explicit would be: `explicitly-null: null`

**Comment by BenedekFarkas** [comment]
I would allow it and seeing the linked example, I'd rather enforce an explicit null in this case (if it plays nicely with GitHub Actions), because whitespace (or lack thereof) should not have syntactical meaning (unless https://en.wikipedia.org/wiki/Whitespace_%28programming_language%29 :D), but YAML is a language where indentation has syntactical meaning, so it's sort of a contradiction.

**Comment by Piedone** [comment]
Are there any similar examples? Because `MAINTENANCE_USER_NAME` and `MAINTENANCE_PASSWORD` should actually have at least a `description` like the others and mustn't be simply set to `null`. So, unless there's something markedly different then these, let's enforce explicit `null`s and fix these by providing proper values.

**Comment by DemeSzabolcs** [comment]
> So, unless there's something markedly different then these, let's enforce explicit `null`s and fix these by providing proper values.

Well there is actually an interesting scenario, in case of 
```
on:
  pull-request:
  push:
    branches:
      - dev
```
(https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/validate-this-gha-refs.yml#L6)

The `pull-request:` line will trigger the warning. We can fix these too by adding null and it will still work, so:

```
on:
  pull-request: null
  push:
    branches:
      - dev
```

Do we want to use the rule still?

**Comment by Piedone** [comment]
Then not, but still fix the two maintenance secrets.

**Comment by DemeSzabolcs** [comment]
> Add the workflow to https://github.com/Lombiq/Hosting-Media-Theme too.

Is this necessary? The workflow in OSOCE (https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/blob/dev/.github/workflows/build-and-test.yml#L73-L78) checks the submodules too. I already fixed the warnings in them.

**Comment by Piedone** [comment]
Then no, not necessary.
