### ISSUE TITLE
Test new GitHub-hosted runners (OSOE-773)

### ISSUE THREAD

**Issue by BenedekFarkas** [Lombiq/Open-Source-Orchard-Core-Extensions#671]
From the [original announcement](https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/):

> From now on, any Linux or Windows workflow triggered from a public repository, using GitHub’s default labels, will run on our faster, more powerful 4-vCPU runners.
...
This upgrade offers increased performance, memory, and storage with 4-vCPUs, 16 GiB of memory and 150GiB storage.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-773)

**Comment by BenedekFarkas** [comment]
This is a bit surprising (as in how low):

> Through the rollout, we have seen real-world improvements of around 25% for GitHub Actions workflows on these new machines without any changes required from you as a developer.

The first full test comparing these runners:
- Root solution:
  - buildjet-4vcpu-ubuntu-2204: 15 minutes 10 seconds
  - ubuntu-22.04: 20 minute timeout
- NuGet solution:
  - buildjet-4vcpu-ubuntu-2204: 5 minutes 13 seconds
  - ubuntu-22.04: 7 minutes 3 seconds (doesn't look it changed meaningfully compared to previous average from 7-8 builds)
- NuGet solution on Windows (not fair comparison due to different core count):
  - gitrunners-windows-2022-x64-8vcpu: 21 minutes 53 seconds
  - windows-2022: 30 minute timeout

No need/sense to change anything now.

**Comment by Piedone** [comment]
Ah, awesome! It should be a lot more for us, and indeed it seems so. Roughly this is where we got this:

![image](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/assets/1976647/94835d32-fdc4-48e0-9534-fd8bab250189)

BuildJet is still better, but that's only Linux. GitRunners with Windows has an issue with long wait times though, sometimes even 15 minutes, which while technically doesn't count against the runtime, still makes you wait longer. Did you count that too?

Related: https://github.com/OrchardCMS/OrchardCore/issues/12583#issuecomment-1898518613

**Comment by BenedekFarkas** [comment]
> GitRunners with Windows has an issue with long wait times though, sometimes even 15 minutes, which while technically doesn't count against the runtime, still makes you wait longer. Did you count that too?

No, although I'm assuming queue times are quite varied. The concrete case I saw for this issue is that GitRunners runner started 2 and a half minutes after GitHub's own (for the same Windows build).

**Comment by Piedone** [comment]
OK!
