### ISSUE TITLE
Failed to start project.

### ISSUE THREAD

**Issue by ChestnutYYY** [Lombiq/Open-Source-Orchard-Core-Extensions#70]
Environment:
IDE: visual studio 2022
Node: 14.15.0
npm: 6.14.12

The operation of gulp keeps reporting errors

The screenshot of the error is as follows
![图片](https://user-images.githubusercontent.com/13895891/158351089-e2e51d6e-6444-461b-aef7-3ee9a1fc9008.png)

Can you help me? thank you  so much.

**Comment by sarahelsaig** [comment]
Hi, we know about it and it will be fixed in an upcoming PR. In the meantime there is a workaround: 
Find the _Lombiq.Npm.Targets_ and _Lombiq.Gulp.Extensions_ projects and build them separately. Then you will be able to build the whole project successfully.

**Comment by Piedone** [comment]
Assuming this to be resolved.
