### ISSUE TITLE
System.InvalidOperationException : The docker.exe pull softwaresecurityproject/zap-stable:2.14.0 --quiet command failed (OSOE-821)

### ISSUE THREAD

**Issue by Psichorex** [Lombiq/Open-Source-Orchard-Core-Extensions#713]
` System.InvalidOperationException : The docker.exe pull softwaresecurityproject/zap-stable:2.14.0 --quiet command failed` this error occures whenever I am trying to run any of the `SecurityScanningTests` on my local machine.
I asked @wAsnk and he confirmed the same thing is happening for him locally. Same error goes locally for the OrchardCore.Commerce solution and NuGet.Test solution.

It is very interesting because we do not experience this on CI neither on Ubuntu nor on Windows builds. At least every OSOCE dev build passed so far and I checked out dev to run tests.

### Repro
1. Run `BasicSecurityScanShouldPass` on your local machine and the error should occur.

### I tried:
1. Upgrading CliWrap nuget to 3.6.6 did not solve this issue that was my best bet.

I suspect something is off with CliWrap and HelpfulLibraries.Cli atleast the logs are suggesting that the `docker daemon` might not be running and the generated test log claims that : `this error may indicate that the docker daemon is not running: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=softwaresecurityproject%2Fzap-stable&tag=2.14.0": open //./pipe/docker_engine: A rendszer nem tal├ílja a megadott f├íjlt.`

Here is the TestOutput.log:
[TestOutput.log](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/files/14406188/TestOutput.log)

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-821)

**Comment by Piedone** [comment]
Is Docker Desktop running?

**Comment by Psichorex** [comment]
> Is Docker Desktop running?

Well it actually did solve my problem. I didn't know about that we should have Docker Desktop Running while OSOCE testing.
