### ISSUE TITLE
Named FlowPart? (OSOE-824)

### ISSUE THREAD

**Issue by devlife** [Lombiq/Open-Source-Orchard-Core-Extensions#717]
Is it possible to have more than one/a named FlowPart on a Content Item? I currently have a "page" which contains a flow part along with several other fields. I would like to do something like this when rendering.

Top FlowPart

Field 1
Field 2

Bottom FlowPart

Field3
Field4

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-824)

**Comment by Piedone** [comment]
This looks like a question better suited for https://github.com/OrchardCMS/OrchardCore/discussions. Please open it there, link it here, and I'll reply to you.
