### ISSUE TITLE
Change all of our NuGet metadata to use license expressions (OSOE-852)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Open-Source-Orchard-Core-Extensions#761]
[NuGet license expressions](https://learn.microsoft.com/en-us/nuget/reference/nuspec#license) make the type of license of a package readily apparent, and help with license checkers, and thus getting adoption for our packages. See https://github.com/aaubry/YamlDotNet/pull/903 for an example of such a change but **that's about nuspec files**.

So, since all of our packages use a BSD-3-Clause license anyway, let's change all of our open-source csprojs from this:

```csproj
<PackageLicenseFile>License.md</PackageLicenseFile>
```

To this:

```csproj
<PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
```

Or if we have nuspec files then to this:

```xml
<license type="expression">BSD-3-Clause</license>
```

- [x] Test the change proposed above with an alpha release of any single-package project first.
- [x] Change all NuGet-published projects of ours.
- [x] Check if lines like `<None Include="License.md" Pack="true" PackagePath="" />` can be removed from csprojs too; most possibly yes, then remove them.
- [x] Update our documentation.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-852)

**Comment by AydinE** [comment]
Have created a [PR](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/789) the only thing I am not sure on is which documentations need to be updated to reflect these changes.

**Comment by Piedone** [comment]
This wiki page: https://lombiq.atlassian.net/wiki/spaces/DEV/pages/2609840133/Preparing+a+.NET+project+to+be+published+on+NuGet

**Comment by Piedone** [comment]
Can you please link to where you tested this?

>  Test the change proposed above with an alpha release of any single-package project first.

**Comment by AydinE** [comment]
Oh I put that under the description of the PR:
https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/789#issue-2343902880

**Comment by Piedone** [comment]
OK, great!
