### ISSUE TITLE
Add VS Code launch files (OSOE-863)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/Open-Source-Orchard-Core-Extensions#774]
Add VS code launch and task files to this repo (and to [Orchard-Training-Demo-Module](https://github.com/Lombiq/Orchard-Training-Demo-Module)) so it's more accessible, particularly outside of Windows. If needed, these files can be copied to our other projects with minimal changes.

Also update the .gitignore file here and in [Open-source-template](https://github.com/Lombiq/Open-source-template).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-863)

**Comment by Piedone** [comment]
Also see https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control/57749909#57749909.
